config/routes.rb
Rails.application.routes.draw do
  resources :groups do 
    member do
      post :join
      delete :leave
    end
  end
  resources :status_updates
  resources :profiles
  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/status_update.rb
class StatusUpdate < ActiveRecord::Base
  belongs_to :user
  validates :status, presence: true

  mount_uploader :image, StatusUpdateImageUploader
end

app/controllers/status_updates_controller.rb
class StatusUpdatesController < ApplicationController

  before_action :set_status_update, only: [:show, :edit, :update, :destroy]

  # GET /status_updates
  # GET /status_updates.json
  def index
    @status_updates = StatusUpdate.all
  end

  # GET /status_updates/1
  # GET /status_updates/1.json
  def show
  end

  # GET /status_updates/new
  def new
    @status_update = StatusUpdate.new
  end

  # GET /status_updates/1/edit
  def edit
  end

  # POST /status_updates
  # POST /status_updates.json
  def create
    @status_update = StatusUpdate.new(status_update_params)
    @status_update.user = current_user

    respond_to do |format|
      if @status_update.save
        format.html { redirect_to :back, notice: 'Status update was successfully created.' }
        format.json { render :show, status: :created, location: @status_update }
      else
        format.html { render :new }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_updates/1
  # PATCH/PUT /status_updates/1.json
  def update
    respond_to do |format|
      if @status_update.update(status_update_params)
        format.html { redirect_to @status_update, notice: 'Status update was successfully updated.' }
        format.json { render :show, status: :ok, location: @status_update }
      else
        format.html { render :edit }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_updates/1
  # DELETE /status_updates/1.json
  def destroy
    @status_update.destroy
    respond_to do |format|
      format.html { redirect_to status_updates_url, notice: 'Status update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_update
      @status_update = StatusUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_update_params
      params.require(:status_update).permit(:status, :image)
    end
end

app/helpers/status_updates_helper.rb
module StatusUpdatesHelper
end

app/views/status_updates/_form.html.erb
<%= simple_form_for(@status_update) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :image %>
    <%= f.input :status, label: false, placeholder: 
    'What are you doing?' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/status_updates/edit.html.erb
<h1>Editing Status Update</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_update %> |
<%= link_to 'Back', status_updates_path %>

app/views/status_updates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Status Updates</h1>

<table>
  <thead>
    <tr>
      <th>Update</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @status_updates.each do |status_update| %>
      <tr>
        <td><%= status_update.update %></td>
        <td><%= status_update.user %></td>
        <td><%= link_to 'Show', status_update %></td>
        <td><%= link_to 'Edit', edit_status_update_path(status_update) %></td>
        <td><%= link_to 'Destroy', status_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status update', new_status_update_path %>

app/views/status_updates/new.html.erb
<h1>New Status Update</h1>

<%= render 'form' %>

<%= link_to 'Back', status_updates_path %>

app/views/status_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Update:</strong>
  <%= @status_update.update %>
</p>

<p>
  <strong>User:</strong>
  <%= @status_update.user %>
</p>
<p>


<%= link_to 'Edit', edit_status_update_path(@status_update) %> |
<%= link_to 'Back', status_updates_path %>