config/routes.rb
Rails.application.routes.draw do
  resources :groups do 
    member do
      post :join
      delete :leave
    end
  end
  resources :status_updates
  resources :profiles
  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :memberships
	has_many :users, through: :memberships



	mount_uploader :logo, GroupLogoUploader
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :join, :leave]

  def join
  @group.users << current_user
  redirect_to :back
end

 def leave
  @group.users.delete(current_user)
  redirect_to :back
end
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @members = @group.users
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end


  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    respond_to do |format| 
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :logo, :owner_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :logo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>
<%= link_to 'Leave', @group %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Logo</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= group.logo %></td>
        <td><%= group.owner_id %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-4">
<div class="card">
  <img class="card-img-top" width="100%" src="<%= @group.logo %>" alt="Card image cap">
  <div class="card-block">
    <h4 class="card-title"><%= @group.name %></h4>
    <p class="card-text">description: <br><%= @group.description %></p>
    <% if current_user.id == @group.owner_id %>
    <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-primary btn-sm" %>
    <% end %>
    <% if @group.users.include?(current_user) %>
    <%= button_to 'Leave', leave_group_path(@group), method: 
    :delete, class: 'btn btn-default' %>
    <% else %>
    <%= button_to 'Join', join_group_path(@group), class: 'btn btn-success' %>
    <% end %>


</div>
</div>
<div class="card card-block">
	<h2 class="card-title">Members<span class="label label-default"><%= @members.count %></span></h2>
	<% @members.each do |member| %>
	<% if member.profile %>
	<p><%= link_to member.profile.full_name,
	profile_path(member.profile) %></p>
	
	<% end %>
<% end %>

</div>
</div>